-- Decade-based themes for LyricGrid Media Manager (63 playlists).
-- Genres 70s-2020s: Country, R&B, Hip-Hop, Reggae, Dancehall Reggae, Funk, Pop
-- Afrobeats 80s-2020s; Rock & Dance 50s-2020s

ALTER TABLE public.themes
  ADD COLUMN IF NOT EXISTS display_order int NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_themes_name_lower_unique
  ON public.themes (lower(trim(name)));

INSERT INTO public.themes (name, category, description, display_order)
SELECT v.name, v.category, v.description, v.display_order
FROM (VALUES
  ('70s Country', 'decade-genre', 'LyricGrid decade playlist: 70s Country', 1),
  ('80s Country', 'decade-genre', 'LyricGrid decade playlist: 80s Country', 2),
  ('90s Country', 'decade-genre', 'LyricGrid decade playlist: 90s Country', 3),
  ('2000s Country', 'decade-genre', 'LyricGrid decade playlist: 2000s Country', 4),
  ('2010s Country', 'decade-genre', 'LyricGrid decade playlist: 2010s Country', 5),
  ('2020s Country', 'decade-genre', 'LyricGrid decade playlist: 2020s Country', 6),
  ('70s R&B', 'decade-genre', 'LyricGrid decade playlist: 70s R&B', 7),
  ('80s R&B', 'decade-genre', 'LyricGrid decade playlist: 80s R&B', 8),
  ('90s R&B', 'decade-genre', 'LyricGrid decade playlist: 90s R&B', 9),
  ('2000s R&B', 'decade-genre', 'LyricGrid decade playlist: 2000s R&B', 10),
  ('2010s R&B', 'decade-genre', 'LyricGrid decade playlist: 2010s R&B', 11),
  ('2020s R&B', 'decade-genre', 'LyricGrid decade playlist: 2020s R&B', 12),
  ('70s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 70s Hip-Hop', 13),
  ('80s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 80s Hip-Hop', 14),
  ('90s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 90s Hip-Hop', 15),
  ('2000s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 2000s Hip-Hop', 16),
  ('2010s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 2010s Hip-Hop', 17),
  ('2020s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 2020s Hip-Hop', 18),
  ('70s Reggae', 'decade-genre', 'LyricGrid decade playlist: 70s Reggae', 19),
  ('80s Reggae', 'decade-genre', 'LyricGrid decade playlist: 80s Reggae', 20),
  ('90s Reggae', 'decade-genre', 'LyricGrid decade playlist: 90s Reggae', 21),
  ('2000s Reggae', 'decade-genre', 'LyricGrid decade playlist: 2000s Reggae', 22),
  ('2010s Reggae', 'decade-genre', 'LyricGrid decade playlist: 2010s Reggae', 23),
  ('2020s Reggae', 'decade-genre', 'LyricGrid decade playlist: 2020s Reggae', 24),
  ('70s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 70s Dancehall Reggae', 25),
  ('80s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 80s Dancehall Reggae', 26),
  ('90s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 90s Dancehall Reggae', 27),
  ('2000s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 2000s Dancehall Reggae', 28),
  ('2010s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 2010s Dancehall Reggae', 29),
  ('2020s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 2020s Dancehall Reggae', 30),
  ('70s Funk', 'decade-genre', 'LyricGrid decade playlist: 70s Funk', 31),
  ('80s Funk', 'decade-genre', 'LyricGrid decade playlist: 80s Funk', 32),
  ('90s Funk', 'decade-genre', 'LyricGrid decade playlist: 90s Funk', 33),
  ('2000s Funk', 'decade-genre', 'LyricGrid decade playlist: 2000s Funk', 34),
  ('2010s Funk', 'decade-genre', 'LyricGrid decade playlist: 2010s Funk', 35),
  ('2020s Funk', 'decade-genre', 'LyricGrid decade playlist: 2020s Funk', 36),
  ('70s Pop', 'decade-genre', 'LyricGrid decade playlist: 70s Pop', 37),
  ('80s Pop', 'decade-genre', 'LyricGrid decade playlist: 80s Pop', 38),
  ('90s Pop', 'decade-genre', 'LyricGrid decade playlist: 90s Pop', 39),
  ('2000s Pop', 'decade-genre', 'LyricGrid decade playlist: 2000s Pop', 40),
  ('2010s Pop', 'decade-genre', 'LyricGrid decade playlist: 2010s Pop', 41),
  ('2020s Pop', 'decade-genre', 'LyricGrid decade playlist: 2020s Pop', 42),
  ('80s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 80s Afrobeats', 43),
  ('90s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 90s Afrobeats', 44),
  ('2000s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 2000s Afrobeats', 45),
  ('2010s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 2010s Afrobeats', 46),
  ('2020s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 2020s Afrobeats', 47),
  ('50s Rock', 'decade-genre', 'LyricGrid decade playlist: 50s Rock', 48),
  ('50s Dance', 'decade-genre', 'LyricGrid decade playlist: 50s Dance', 49),
  ('60s Rock', 'decade-genre', 'LyricGrid decade playlist: 60s Rock', 50),
  ('60s Dance', 'decade-genre', 'LyricGrid decade playlist: 60s Dance', 51),
  ('70s Rock', 'decade-genre', 'LyricGrid decade playlist: 70s Rock', 52),
  ('70s Dance', 'decade-genre', 'LyricGrid decade playlist: 70s Dance', 53),
  ('80s Rock', 'decade-genre', 'LyricGrid decade playlist: 80s Rock', 54),
  ('80s Dance', 'decade-genre', 'LyricGrid decade playlist: 80s Dance', 55),
  ('90s Rock', 'decade-genre', 'LyricGrid decade playlist: 90s Rock', 56),
  ('90s Dance', 'decade-genre', 'LyricGrid decade playlist: 90s Dance', 57),
  ('2000s Rock', 'decade-genre', 'LyricGrid decade playlist: 2000s Rock', 58),
  ('2000s Dance', 'decade-genre', 'LyricGrid decade playlist: 2000s Dance', 59),
  ('2010s Rock', 'decade-genre', 'LyricGrid decade playlist: 2010s Rock', 60),
  ('2010s Dance', 'decade-genre', 'LyricGrid decade playlist: 2010s Dance', 61),
  ('2020s Rock', 'decade-genre', 'LyricGrid decade playlist: 2020s Rock', 62),
  ('2020s Dance', 'decade-genre', 'LyricGrid decade playlist: 2020s Dance', 63)
) AS v(name, category, description, display_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.themes t WHERE lower(trim(t.name)) = lower(trim(v.name))
);

UPDATE public.themes t
SET display_order = v.display_order,
    category = COALESCE(v.category, t.category),
    description = v.description
FROM (VALUES
  ('70s Country', 'decade-genre', 'LyricGrid decade playlist: 70s Country', 1),
  ('80s Country', 'decade-genre', 'LyricGrid decade playlist: 80s Country', 2),
  ('90s Country', 'decade-genre', 'LyricGrid decade playlist: 90s Country', 3),
  ('2000s Country', 'decade-genre', 'LyricGrid decade playlist: 2000s Country', 4),
  ('2010s Country', 'decade-genre', 'LyricGrid decade playlist: 2010s Country', 5),
  ('2020s Country', 'decade-genre', 'LyricGrid decade playlist: 2020s Country', 6),
  ('70s R&B', 'decade-genre', 'LyricGrid decade playlist: 70s R&B', 7),
  ('80s R&B', 'decade-genre', 'LyricGrid decade playlist: 80s R&B', 8),
  ('90s R&B', 'decade-genre', 'LyricGrid decade playlist: 90s R&B', 9),
  ('2000s R&B', 'decade-genre', 'LyricGrid decade playlist: 2000s R&B', 10),
  ('2010s R&B', 'decade-genre', 'LyricGrid decade playlist: 2010s R&B', 11),
  ('2020s R&B', 'decade-genre', 'LyricGrid decade playlist: 2020s R&B', 12),
  ('70s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 70s Hip-Hop', 13),
  ('80s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 80s Hip-Hop', 14),
  ('90s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 90s Hip-Hop', 15),
  ('2000s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 2000s Hip-Hop', 16),
  ('2010s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 2010s Hip-Hop', 17),
  ('2020s Hip-Hop', 'decade-genre', 'LyricGrid decade playlist: 2020s Hip-Hop', 18),
  ('70s Reggae', 'decade-genre', 'LyricGrid decade playlist: 70s Reggae', 19),
  ('80s Reggae', 'decade-genre', 'LyricGrid decade playlist: 80s Reggae', 20),
  ('90s Reggae', 'decade-genre', 'LyricGrid decade playlist: 90s Reggae', 21),
  ('2000s Reggae', 'decade-genre', 'LyricGrid decade playlist: 2000s Reggae', 22),
  ('2010s Reggae', 'decade-genre', 'LyricGrid decade playlist: 2010s Reggae', 23),
  ('2020s Reggae', 'decade-genre', 'LyricGrid decade playlist: 2020s Reggae', 24),
  ('70s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 70s Dancehall Reggae', 25),
  ('80s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 80s Dancehall Reggae', 26),
  ('90s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 90s Dancehall Reggae', 27),
  ('2000s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 2000s Dancehall Reggae', 28),
  ('2010s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 2010s Dancehall Reggae', 29),
  ('2020s Dancehall Reggae', 'decade-genre', 'LyricGrid decade playlist: 2020s Dancehall Reggae', 30),
  ('70s Funk', 'decade-genre', 'LyricGrid decade playlist: 70s Funk', 31),
  ('80s Funk', 'decade-genre', 'LyricGrid decade playlist: 80s Funk', 32),
  ('90s Funk', 'decade-genre', 'LyricGrid decade playlist: 90s Funk', 33),
  ('2000s Funk', 'decade-genre', 'LyricGrid decade playlist: 2000s Funk', 34),
  ('2010s Funk', 'decade-genre', 'LyricGrid decade playlist: 2010s Funk', 35),
  ('2020s Funk', 'decade-genre', 'LyricGrid decade playlist: 2020s Funk', 36),
  ('70s Pop', 'decade-genre', 'LyricGrid decade playlist: 70s Pop', 37),
  ('80s Pop', 'decade-genre', 'LyricGrid decade playlist: 80s Pop', 38),
  ('90s Pop', 'decade-genre', 'LyricGrid decade playlist: 90s Pop', 39),
  ('2000s Pop', 'decade-genre', 'LyricGrid decade playlist: 2000s Pop', 40),
  ('2010s Pop', 'decade-genre', 'LyricGrid decade playlist: 2010s Pop', 41),
  ('2020s Pop', 'decade-genre', 'LyricGrid decade playlist: 2020s Pop', 42),
  ('80s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 80s Afrobeats', 43),
  ('90s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 90s Afrobeats', 44),
  ('2000s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 2000s Afrobeats', 45),
  ('2010s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 2010s Afrobeats', 46),
  ('2020s Afrobeats', 'decade-genre', 'LyricGrid decade playlist: 2020s Afrobeats', 47),
  ('50s Rock', 'decade-genre', 'LyricGrid decade playlist: 50s Rock', 48),
  ('50s Dance', 'decade-genre', 'LyricGrid decade playlist: 50s Dance', 49),
  ('60s Rock', 'decade-genre', 'LyricGrid decade playlist: 60s Rock', 50),
  ('60s Dance', 'decade-genre', 'LyricGrid decade playlist: 60s Dance', 51),
  ('70s Rock', 'decade-genre', 'LyricGrid decade playlist: 70s Rock', 52),
  ('70s Dance', 'decade-genre', 'LyricGrid decade playlist: 70s Dance', 53),
  ('80s Rock', 'decade-genre', 'LyricGrid decade playlist: 80s Rock', 54),
  ('80s Dance', 'decade-genre', 'LyricGrid decade playlist: 80s Dance', 55),
  ('90s Rock', 'decade-genre', 'LyricGrid decade playlist: 90s Rock', 56),
  ('90s Dance', 'decade-genre', 'LyricGrid decade playlist: 90s Dance', 57),
  ('2000s Rock', 'decade-genre', 'LyricGrid decade playlist: 2000s Rock', 58),
  ('2000s Dance', 'decade-genre', 'LyricGrid decade playlist: 2000s Dance', 59),
  ('2010s Rock', 'decade-genre', 'LyricGrid decade playlist: 2010s Rock', 60),
  ('2010s Dance', 'decade-genre', 'LyricGrid decade playlist: 2010s Dance', 61),
  ('2020s Rock', 'decade-genre', 'LyricGrid decade playlist: 2020s Rock', 62),
  ('2020s Dance', 'decade-genre', 'LyricGrid decade playlist: 2020s Dance', 63)
) AS v(name, category, description, display_order)
WHERE lower(trim(t.name)) = lower(trim(v.name));

NOTIFY pgrst, 'reload schema';
